[package]
name = "calculator"
version = "0.1.1"
authors = ["ajayrwarrier <ajayrwarrier@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
